#!/bin/bash

echo "  _    _ _   _ _ _ _            _____           _       _         __  __                                   ";
echo " | |  | | | (_| (_| |          / ____|         (_)     | |       |  \/  |                                  ";
echo " | |  | | |_ _| |_| |_ _   _  | (___   ___ _ __ _ _ __ | |_ ___  | \  / | __ _ _ __   __ _  __ _  ___ _ __ ";
echo " | |  | | __| | | | __| | | |  \___ \ / __| '__| | '_ \| __/ __| | |\/| |/ _\` | '_ \ / _\` |/ _\` |/ _ | '__|";
echo " | |__| | |_| | | | |_| |_| |  ____) | (__| |  | | |_) | |_\__ \ | |  | | (_| | | | | (_| | (_| |  __| |   ";
echo "  \____/ \__|_|_|_|\__|\__, | |_____/ \___|_|  |_| .__/ \__|___/ |_|  |_|\__,_|_| |_|\__,_|\__, |\___|_|   ";
echo "                        __/ |                    | |                                        __/ |          ";
echo "                       |___/                     |_|                                       |___/           ";

REPO_URL="https://raw.githubusercontent.com/lagie-marin/utility-scripts-template/main/"
SCRIPTS=("script-manager" "getlib" "addc" "addh" "adds" "addt" "push" "translate_csr")
LOCAL_FOLDER="/usr/local/bin/"
DEST_FOLDER="/usr/utility-scripts-template/"

mkdir -p "$DEST_FOLDER"
sudo chmod +x "$LOCAL_FOLDER/"

for script in "${SCRIPTS[@]}"; do
    if [ "$script" == "getlib" ]; then
        read -p "Do you want to use 'getlib' (y/n)? " choice
        if [ "$choice" == "y" ] || [ "$choice" == "Y" ]; then
            while true; do
                read -p "Enter the HTTPS link to the library repository: " lib_repo
                if [[ "$lib_repo" =~ ^https://.*\.git$ ]]; then
                    sudo chown $USER "$LOCAL_FOLDER/$script"
                    sudo curl -L "$REPO_URL/$script" -o "$LOCAL_FOLDER/$script"
                    sudo chmod +x "$LOCAL_FOLDER/$script"
                    sudo sed -i "6i git clone $lib_repo" "$LOCAL_FOLDER/$script"
                    break
                else
                    echo "Invalid URL. It should start with 'https://' and end with '.git'. Please try again."
                fi
            done
        else
            echo "Skipping 'getlib'."
        fi
    else
        sudo chown $USER "$LOCAL_FOLDER/$script"
        sudo curl -L "$REPO_URL/$script" -o "$LOCAL_FOLDER/$script"
        sudo chmod +x "$LOCAL_FOLDER/$script"
    fi
done

echo "The scripts have been successfully downloaded."
