#!/bin/bash
REPO_URL="https://raw.githubusercontent.com/lagie-marin/utility-scripts-template/main/"
SCRIPTS=("script-manager" "getlib" "addc" "addh" "adds" "addt" "push")
LOCAL_FOLDER="/usr/local/bin/"

for script in "${SCRIPTS[@]}"; do
    if [ "$script" == "getlib" ]; then
        read -p "Do you want to use 'getlib' (y/n)? " choice
        if [ "$choice" == "y" ] || [ "$choice" == "Y" ]; then
            while true; do
                read -p "Enter the HTTPS link to the library repository: " lib_repo
                if [[ "$lib_repo" =~ ^https://.*\.git$ ]]; then
                    sudo chown $USER "$LOCAL_FOLDER/$script"
                    sudo curl -L "$REPO_URL/$script" -o "$LOCAL_FOLDER/$script"
                    sudo chmod +x "$LOCAL_FOLDER/$script"
                    sudo sed -i "3igit clone $lib_repo" "$LOCAL_FOLDER/$script"
                    break
                else
                    echo "Invalid URL. It should start with 'https://' and end with '.git'. Please try again."
                fi
            done
        else
            echo "Skipping 'getlib'."
        fi
    else
        sudo chown $USER "$LOCAL_FOLDER/$script"
        sudo curl -L "$REPO_URL/$script" -o "$LOCAL_FOLDER/$script"
        sudo chmod +x "$LOCAL_FOLDER/$script"
    fi
done

echo "The scripts have been successfully downloaded."
